### ISSUE TITLE
What are the image libraries for? (In requirements.txt)

### ISSUE THREAD

**Issue by Dr-zzt** [scottmsul/FactorioQualityOptimizer#3]
I see matplotlib and Pillow but it seems that your code is not using those at the moment, and the final program seems to use console only.
Are you planning to add GUI later?

**Comment by scottmsul** [comment]
Good question, not sure how those got in there. Usually when I setup requirements files I just run `pip freeze > requirements.txt` to always get the exact setup every single time. Either I installed those at some point to look at a plot, or those are dependencies of numpy and were automatically installed with it.

Right now I'm actually working on switching it to a linear solver, as that would potentially allow more steps of production and maybe even using actual factorio recipes instead of a single abstract step.

No plans for a GUI at the moment. If I were to go for that level of user-friendliness I'd probably go for a web app over a python gui.

**Comment by Dr-zzt** [comment]
Thank you for your answer!
