### ISSUE TITLE
How to solve the optimal configuration in a chain of product?

### ISSUE THREAD

**Issue by zzh8829** [scottmsul/FactorioQualityOptimizer#9]
As an example
 
copper ore -> copper plate (smelter)
copper plate -> copper wire (assembler)

the cost function in this setup would be calculate the least number of copper ore needed to obtain 1 copper wire at quality Q.

the idea behind this question is to settle the debate of most efficient quality production in a regular factory outside of looping recyclers (which is already modeled today)

- use quality modules in smelter and assembler, recycle both copper wire and copper plate
- use quality modules in smelter and assembler, recycle only copper plate
- use prod module in smelter and assembler, recycle both copper wire and copper plate
- use prod module in smelter and assembler, recycle only copper plate
- use a mix of quality and prod modules

I cant think of a simple intutive answer for this, so this seems like a task only optimzer can solve.
This gets especially crazy when you factor in different variation of buildings and productivity bonus.

Looks like the ortools based solver has a real chance at answering this question.

**Comment by zzh8829** [comment]
When I run the electronic_circuits example it seems to suggest crafting and recycling belt and underground belts in foundry, is that an reliable answer?

I tried this as a practical example
```json
{
  "data": "data/space-age-2.0.11.json",
  "quality_module_tier": 3,
  "quality_module_quality": "legendary",
  "prod_module_tier": 3,
  "prod_module_quality": "legendary",
  "speed_module_tier": 3,
  "speed_module_quality": "legendary",
  "building_quality": "legendary",
  "max_quality_unlocked": "legendary",
  "module_cost": 1,
  "building_cost": 1,
  "allowed_crafting_machines": [
    "assembling-machine-3",
    "electric-furnace",
    "electric-mining-drill",
    "recycler"
  ],
  "inputs": [
    {
      "key": "copper-ore",
      "quality": "normal",
      "resource": false,
      "cost": 1.0
    }
  ],
  "outputs": [
    {
      "key": "copper-cable",
      "quality": "legendary",
      "amount": 1.0
    }
  ]
}

```

looks like it's suggesting 

```
Machine layout:
Copper cable in Assembling machine 3: uncommon 3Q1P, rare 2Q2P, epic 2Q2P, legendary 4P
Copper cable (recycling) in Recycler: uncommon 4Q, rare 4Q, epic 4Q
Copper ore (recycling) in Recycler: normal 4Q
Copper plate in Electric furnace: uncommon 2Q, rare 1Q1P, epic 1Q1P, legendary 2P
```
This is very surprising if i read it the result correctly its suggesting that I should NOT smelt normal copper ore but recycle them into uncommon first.

**Comment by zzh8829** [comment]
I found some very strange ideas from the solver but kind make sense
for example a great way to get quality iron plate is to recycle iron chest.
and a great way to get circuits and it recycle combinators?? these are very cool ideas i have to look into how the optimizer is setup.

**Comment by scottmsul** [comment]
One thing to keep in mind is that the probability of jumping only one quality is much higher than jumping two or more qualities. For instance the probability of one quality increase is 22.3% for four t3 legendary quality modules, as opposed to the hard-coded 10% for each additional quality increase in a single step. Intuitively I think this makes it better to spread out large quality increases over several stages of production, especially with the 25% recycling penalty from going down and back up again. So instead of going from normal A -> legendary B by recycling all rare B or below, it's better to do something that involves A -> B -> C and recycling C -> B for various qualities of A/B/C, or maybe even A -> B -> C -> D. For instance I was playing around with crafting legendary iron plates and it often makes underground belts or underground pipes in foundries and breaks them back down.

**Comment by zzh8829** [comment]
I also noticed an weird issue if i set the output quality to rare (very needed early game to bootstrap quality) the solver will start suggesting random recipe to recycle epic and quality products. is there a way to make the solver keep the high quality product other than setting "max qaulity"? max quality could work but its not realistic since i would have epic unlocked already but still trying to collect rare+ products.

**Comment by zzh8829** [comment]
> One thing to keep in mind is that the probability of jumping only one quality is much higher than jumping two or more qualities. For instance the probability of one quality increase is 22.3% for four t3 legendary quality modules, as opposed to the hard-coded 10% for each additional quality increase in a single step. Intuitively I think this makes it better to spread out large quality increases over several stages of production, especially with the 25% recycling penalty from going down and back up again. So instead of going from normal A -> legendary B by recycling all rare B or below, it's better to do something that involves A -> B -> C and recycling C -> B for various qualities of A/B/C, or maybe even A -> B -> C -> D. For instance I was playing around with crafting legendary iron plates and it often makes underground belts or underground pipes in foundries and breaks them back down.

I was suspicious of the copper ore recycling so I looked into the configuration again. 
When i set module cost to 0.01 
```
Objective value = 9.184994432741718

Inputs used:
input__normal__copper-ore: 8.301236514364586

Buildings used: 23.578259888868544

Modules used: 64.79753194884454

Machine layout:
Copper cable in Assembling machine 3: normal 4Q, uncommon 4Q, rare 4P
Copper cable (recycling) in Recycler: normal 4Q, uncommon 4Q
Copper plate in Electric furnace: normal 2Q
```

compare to the default 1
```
Objective value = 56.72250727001281

Inputs used:
input__normal__copper-ore: 26.776499483419087

Buildings used: 8.46712935420997

Modules used: 29.861336493051624

Machine layout:
Copper cable in Assembling machine 3: uncommon 4Q, rare 4P
Copper cable (recycling) in Recycler: uncommon 4Q
Copper ore (recycling) in Recycler: normal 4Q
Copper plate in Electric furnace: uncommon 2Q, rare 2P

Recipes used:
uncommon__copper-cable__assembling-machine-3__4-qual__0-prod__0-beaconed-speed: 0.5698385740247309
rare__copper-cable__assembling-machine-3__0-qual__4-prod__0-beaconed-speed: 0.2329745559537295
uncommon__copper-cable-recycling__recycler__4-qual__0-prod__0-beaconed-speed: 0.31056202284347834
normal__copper-ore-recycling__recycler__4-qual__0-prod__0-beaconed-speed: 5.350163739493903
uncommon__copper-plate__electric-furnace__2-qual__0-prod__0-beaconed-speed: 1.7531416541573628
rare__copper-plate__electric-furnace__0-qual__2-prod__0-beaconed-speed: 0.25044880773676603
```


Base config
```
  "data": "data/space-age-2.0.11.json",
  "quality_module_tier": 3,
  "quality_module_quality": "uncommon",
  "prod_module_tier": 3,
  "prod_module_quality": "uncommon",
  "speed_module_tier": 3,
  "speed_module_quality": "uncommon",
  "building_quality": "normal",
  "max_quality_unlocked": "rare",
  "module_cost": 1,
  "building_cost": 0.01,
  "allowed_crafting_machines": [
    "assembling-machine-3",
    "electric-furnace",
    "electric-mining-drill",
    "recycler"
  ],
  "inputs": [
    {
      "key": "copper-ore",
      "quality": "normal",
      "resource": false,
      "cost": 1.0
    }
  ],
  "outputs": [
    {
      "key": "copper-cable",
      "quality": "rare",
      "amount": 1.0
    }
  ]
  ```

is it fair to say in this example the default module cost is way too high? do you have some suggestion on how to balance module cost and building cost. 

base on this setup it does seem like for my original question, the solver suggest that
- use quality modules in smelter and assembler, recycle only copper cable, dont recycle plate is the most optimal setup for the objective of using uncommon modules to obtain rare cable from common ore?

there are a lot of variables and the solver give really different results a lot of time.

**Comment by zzh8829** [comment]
This project has been tremendously helpful to answer my curiosity, I would like to make some graphical UI for this. could be rendering layout as an image or even a full web frontend. Do you think something like that could fit in this project?

**Comment by zzh8829** [comment]
![image](https://github.com/user-attachments/assets/bb3b2802-a0c0-494d-be9a-25058280895c)

this is an example i generated with claude

**Comment by scottmsul** [comment]
> is it fair to say in this example the default module cost is way too high? do you have some suggestion on how to balance module cost and building cost.
> 
> base on this setup it does seem like for my original question, the solver suggest that
> 
>     * use quality modules in smelter and assembler, recycle only copper cable, dont recycle plate is the most optimal setup for the objective of using uncommon modules to obtain rare cable from common ore?
> 
> 
> there are a lot of variables and the solver give really different results a lot of time.

Note that the solver units are items/sec.

On the one hand, I think balancing module cost with input cost is somewhat subjective and situational. If you're trying to setup an initial t3 legendary module factory that itself uses t3 legendary modules everywhere, it might be easier to setup another 1/sec of mining than to make another really expensive module. On the other hand if you've already mass-produced chests full of modules it might make more sense to minimize inputs over modules.

Perhaps a more objective way to think about it is the following. Suppose we have some "recursive" factory that makes assemblers, mining drills, and modules in the same proportion as itself. What cost function should it use to minimize the time needed to make a copy itself? To keep things simple we'll just use normal mining drills make things on Nauvis. 1/sec of iron/copper can be done with 2 mining drills. A quick check from kirkmcdonald's calculator shows two mining drills requires [55 ore](https://kirkmcdonald.github.io/calc.html#zip=hVbLctswDPybnMqZJO2pGd/6IxAFS6wpQgXJuOrXd6lXJFmZXGwSAAFysQBUU6JL7MmyoYbNq3k2Ly9PSokv8anKztcuNPFSucZ0LmBtanXeP7nEXbywZ5vU2Z3up/58ferVibo0XKjrJDiy5E0Un5OTcHl5/tYyvQ9GnC+bO8JpWXh6J/y/Wc01L9qrz3AV2LxzSKOVS63LnamKtAhi9tdcrkHW1abhIU7uENTiolhiLeTnRd+zGtFJ7lTCuolWqZ9WScIkSxkAJP4wykqhhF/2v9n7ARbduBtyRzcxSXnUvo1vMxWp8hx/edtW2HNS8QyvDcWtwrumTUfrFbydZQYelkLaCvfIbBQjqHLj8kzTSvpUZ8VvD779MonCzXRk25KTJofxzC9kp3XW84lmZQkH1mYwLgCSKyg3670LN66NbTmmWVS7aFtSMLLmK4fIRrmTtJwYr3D11HFqVe5jtkdPhMCxB0HSh2zyXrFfnJMm0JR1gB+ESIW5O/eVzwwCh/U2bCXEpNkW+poeYcLqfzU2lchtFvYq5W6FJgRqqLjyvhwWfXRdD6xAaNSIuYPQ5iq6InKilvsmZFZsQHT8UpJFbMWFhyfeqcGVwYsgaz66Hl47qTNiRC/LM2PvatZUCkLFIv/AMwekRc3r1yYvX5v8+Nrk+zbDu1tH6zisCFEDQmWfUIx+URm0sQXgygkI1FX8Ac5Y9hVZpMPRItVBACO4WZKaHqQnnic2S0dNAHX2B4+6k+PXHAuHjrmbxcq43yoce9PhxmNDGJstKrOEE33QqNSzTN5RcagQEGhsUyEntGHnNzS5OuuA4Zl6c3pua+dnH5U9qEu91Iab5rEkTmD5k4EiVLCyHOP6KGU7oKss21Z8t+29hUtldp14RGfIpfQALfujTP662v1b3S4jZkVyP2Am+i2jAU8/nWlFs6A4bydg5s3DJChEO5kFBb1PpsGc5McTpxMB1mczAW/5bCrMSHwyFw7aw2QYi27/lbCckhxqHeYdSEDeZ23O6wMVXcmxh0/ChMEbe9G0beaTCgFGquJ/rzzM7jIixk+M5/8=) (46 iron + 9 copper), and 1 t3 prod module requires roughly [2500 ore](https://kirkmcdonald.github.io/calc.html#zip=hVVLctswDL1NVuVM3HaVjHe9CETBEmuKUEHSrnr6PuoXWVYmG4n4EACBB6CmROfYk2VDDZvv5tWcTi9Kic/xpcrO1y408Vy5xnQu4Gxqdd6/uMRdPPcqdbbJ3VwaTIezZ/PjTd9OL706UXDP1HUSHFnyJorPyUk4n16/tUy3wYjzhbjDnZaDpxvh/24117xILz7DVGBz45BGLZdalztTFW5hxOwvWZ01ZF1tGh7iZA5OLQLFEWchPx/6ntWITnynElYiWqV+OiUJEy9lJCDxh1JWCsX9Qv9m7wdodCM15I6uYpLyKH0f32YqUuXZ//K2LbPnpOIZVhuKW4F3TZv22mvyHjQz8mEppC3zMTMbwZhUuXJ5pmklfSqz4rcX33+ZROFqOrJtqUmTw3jnF6rTOov6P0vYs00lCA6szWBcQEougNws9y5cuTa25ZhmVu2ibUmByJovHCIb5U7ScmMM4eKp49Sq3Mdqj5YIjmMPgKQP3mS9Yr8YJ02AMOsAO3CRCqofzFc+MwAc1mjYSohJC9SBlh5uwmp/VTaVyHVmojFKbAUmBGiouPK+HBZ5dF2PXAHQpXPuALS5iK4ZORDLfeMyKwgAHV9KsrCtuPD0xDs1CBm4CLLWo+s/2jV6WZ4Ze1ezptIQKhb1Rz5zQFnUfP9a5fS1ys+vVX5sK/wQdbSOw5ohagCo7BOa0S8igzG2JHg/sFa2AFddxR85G6dBRRZVcrRwdRBkF5AttU5P3AOHE8iloyYAUY8X97KD6xfJodZhoXIsQNsXeGYrI9qVOQ6wXfzj1Bgfj/YtzkWfJBjdMw9IJe+zNsehyQ1diy4DCMdRF3LCKHd+A7WLsw51OBJvbs+j8fjus7AH/KmX2nDTPLfVQaB/MlIOEbQsx7i+WdkOmEwL2YrvtvO74LHsvwOLmC65tC8yz37Pk7+udv9Ws4BiJfvhMzETNkbsRdN2Ck0iVH3MD/5b4bLz1qo9brypH5ZdVWztdhRSe7h3pyF5W3CyFGwmpxrMxNPiKg1wsLpKoT5ZXjPcnm8cLjBoH60wvPSzJTbn6ZM1tpPuFtl/) (900 iron and 1600 copper), meaning the cost function of modules should be 45x that of inputs! So if anything the default module cost is way too *low*. I know this comparison isn't perfect since it ignores modules in the resource calculation, but I think the point still remains, that in general setting up 1/sec of a new input is actually quite small compared to making a t3 module. Though who knows, maybe it's closer to 1:1 really-late game once you factor in all the crazy prod bonuses.

**Comment by scottmsul** [comment]
> This project has been tremendously helpful to answer my curiosity, I would like to make some graphical UI for this. could be rendering layout as an image or even a full web frontend. Do you think something like that could fit in this project?

I wasn't specifically planning on implementing this, but love the idea if you wanted to try it! For a web frontend, were you thinking of maybe something like a Flask entrypoint that would allow users to run their own local server?

**Comment by scottmsul** [comment]
I went ahead and merged the PR, and added fixes for the couple things I mentioned. BTW the circular imports can be resolved by using `import library` and `library.func()` instead of `from library import func`. It has something to do with the `from` syntax basically trying to run everything in the file whereas the plain `import` syntax does not.

**Comment by scottmsul** [comment]
I'm going to go ahead and close this issue, since this "issue" is mostly discussion and not an actual problem with the library. If you're interested in having more discussions about this library, or linear solvers in general, there's a dedicated thread in the Factorio discord. If you join the official Factorio discord, search for the Quality channel (under the Space Age channel group), inside the Quality channel is a thread called "Thread for LP nonsense!" that I'm pretty active in.
